const {
  AWAKE_NODE_ENV,
  AWAKE_DEV_PORT,
  AWAKE_DEV_DATABASE_URL,
  AWAKE_DEV_ALLOWABLE_ORIGINS,
  AWAKE_DEV_ENCODING_AUTHENTICATION_SECRET
} = process.env;

export default {
  AWAKE_NODE_ENV,
  AWAKE_PORT: AWAKE_DEV_PORT,
  AWAKE_DATABASE_URL: AWAKE_DEV_DATABASE_URL,
  AWAKE_ALLOWABLE_ORIGINS: AWAKE_DEV_ALLOWABLE_ORIGINS,
  AWAKE_ENCODING_AUTHENTICATION_SECRET: AWAKE_DEV_ENCODING_AUTHENTICATION_SECRET
};
