const {
  PROJECT_NODE_ENV,
  PROJECT_DEV_PORT,
  PROJECT_DEV_DATABASE_URL,
  PROJECT_DEV_ALLOWABLE_ORIGINS
} = process.env;

export default {
  PROJECT_NODE_ENV,
  PROJECT_PORT: PROJECT_DEV_PORT,
  PROJECT_DATABASE_URL: PROJECT_DEV_DATABASE_URL,
  PROJECT_ALLOWABLE_ORIGINS: PROJECT_DEV_ALLOWABLE_ORIGINS
};
