const {
  AWAKE_NODE_ENV,
  AWAKE_PROD_PORT,
  AWAKE_PROD_DATABASE_URL,
  AWAKE_PROD_ALLOWABLE_ORIGINS
} = process.env;

export default {
  AWAKE_NODE_ENV,
  AWAKE_PORT: AWAKE_PROD_PORT,
  AWAKE_DATABASE_URL: AWAKE_PROD_DATABASE_URL,
  AWAKE_ALLOWABLE_ORIGINS: AWAKE_PROD_ALLOWABLE_ORIGINS
};
