const {
  AWAKE_NODE_ENV,
  AWAKE_TEST_PORT,
  AWAKE_TEST_DATABASE_URL,
  AWAKE_TEST_ALLOWABLE_ORIGINS
} = process.env;

export default {
  AWAKE_NODE_ENV,
  AWAKE_PORT: AWAKE_TEST_PORT,
  AWAKE_DATABASE_URL: AWAKE_TEST_DATABASE_URL,
  AWAKE_ALLOWABLE_ORIGINS: AWAKE_TEST_ALLOWABLE_ORIGINS
};

