const {
  PROJECT_NODE_ENV,
  PROJECT_TEST_PORT,
  PROJECT_TEST_DATABASE_URL,
  PROJECT_TEST_ALLOWABLE_ORIGINS
} = process.env;

export default {
  PROJECT_NODE_ENV,
  PROJECT_PORT: PROJECT_TEST_PORT,
  PROJECT_DATABASE_URL: PROJECT_TEST_DATABASE_URL,
  PROJECT_ALLOWABLE_ORIGINS: PROJECT_TEST_ALLOWABLE_ORIGINS
};
